name: AetherUI
version: 1.0-SNAPSHOT
main: com.theangel256.aetherui.Main
api-version: 1.20
authors: [Theangel256]
description: A scalable GUI framework.
commands:
  aetherui:
    description: Opens the demo GUI
    usage: /aetherui
