name: NexusInventories
version: ${project.version}
main: theangel256.nexusinventories.Main
api-version: 1.20
authors: [Theangel256]
description: A scalable GUI framework.
commands:
  nexusinventories:
    description: Opens the demo GUI
    usage: /nexusinventories
